### PR TITLE
Fix range of styling issues identified by precommit config

### PR DESCRIPTION
**Pull request by timvink**
#98

### CODE REVIEW

**Review by Matgrb — APPROVED** [review]
Looks good. Only make sure that the unit tests succeed

**Comment by timvink** [comment]
@Matgrb I cannot find this bug :(. Somehow, a single value changed from 0 to 0.5. As far as I can see, I only changed docstrings and other styling issues. Can you have a look? You wrote the code, perhaps you know better where to look / where it could potentially change the shap value.

**Comment by Matgrb** [comment]
I think the issue was this line:
```
from sklearn.experimental import enable_iterative_imputer  # noqa
```

It did not have the `#noqa` at the end, so the pre-commit has removed this line. I suppose now the issue should be fixed.

**Comment by timvink** [comment]
Thnx Mateusz! Still don't know what the issue was but trust it's fine :)

**Comment by Matgrb** [comment]
It was a weird shap related issue.

initially this test was checking if the mean shap value was 0.5. Then with some updates, the value has suddenly changed to 0. Now it is back at 0.5.

I have decided to disregard the mean shap value for now, since it is the mean abs shap value that is the most important there.
In the future, we can replace the shap based unit tests with mocks to ensure full stability.

**Pull request merged**
