### PR TITLE
closing issue: Add references to stats tests methods #28

### PR DESCRIPTION
**Pull request by dattanibedita**
Please let me know for any further edits.

### CODE REVIEW

**Comment by Matgrb** [comment]
Thank you for making the PR, unfortunately, we cannot merge this PR.

First of all, the process of making changes is first via making the issue and discussing it, and then making the changes that are decided. The workflow is indicateed in the CONTRIBUTING file.

In case of this PR, I suppose the changes that you have made are not helpful for the package for the following reasons:
- We do not provide docstrings for the tests, and we are not planning on it in the nearest future,
- They do not follow the docstrings convention we use in probatus,
- The quality of the docstrings is too low. 

I will close this PR. If you have a good idea on how to improve the package please make an issue and discuss it first, or pick up existing issue.

**Comment by dattanibedita** [comment]
Hi Mateusz,

Thank you for the update. Actually, this is my first Open-Source
contribution. I was not aware of the conventions. I was trying to close
issue #28. After reading your email, I get that I have to comment on issue
#28 and follow the discussion thereafter to open a pull request. I will
surely be doing that.

Thanks and Regards,
Nibedita.

**Comment by Matgrb** [comment]
I understand, We would be really glad if you picked that issue up.
 
The issue should be described a bit better when I created it, I see now why there is confusion. I will improve the description and let's discuss in the issue whether you would like to pick it up.

**Comment by Matgrb** [comment]
I have updated the description of the issue. Please let us know in #28 if you would like to pick it up and if you need any help with it or additional explanation.

**Comment by dattanibedita** [comment]
Thank you. I will be commenting on the issue thread after I go in through the detail.

**Pull request closed without merging**
