### PR TITLE
Correct mask dimension

### PR DESCRIPTION
**Pull request by gverbock**
Pull request based on #176

### CODE REVIEW

**Comment by gverbock** [comment]
@Matgrb @timvink I made a PR on what I believe is a bug in the implementation of the mask. It introduces fluctuations in the shap value between for example train and test. 

I believe one could also go further and make the masking optional for algorithm that are not Linear Regressions.

**Review by Matgrb — APPROVED** [review]
Thanks for implementing the fix!

Indeed that might have been a bug. Is this finished and ready to merge?

**Comment by gverbock** [comment]
Yes, this is finished. I will remove the draft status.

**Comment by gverbock** [comment]
@Matgrb Can I merge, I see you approved so I guess it is ready to go.

**Pull request merged**
