### PR TITLE
Add compatibility for Python 3.12

### PR DESCRIPTION
**Pull request by ReinierKoops**
Fixes the deprecation/renaming of SHAP code

### CODE REVIEW

**Comment by ReinierKoops** [comment]
This should fix: https://github.com/ing-bank/probatus/issues/234 and https://github.com/ing-bank/probatus/issues/233

**Comment by ReinierKoops** [comment]
@adri0 it is finally succeeded and ready for review ;)

**Comment by adri0** [comment]
Maybe you can add python 3.12 to the [unit test matrix in the workflow](https://github.com/ing-bank/probatus/blob/bd831536d70554eafa74d656a8de8259245b924e/.github/workflows/unit_tests.yml#L26).

**Comment by ReinierKoops** [comment]
> Maybe you can add python 3.12 to the [unit test matrix in the workflow](https://github.com/ing-bank/probatus/blob/bd831536d70554eafa74d656a8de8259245b924e/.github/workflows/unit_tests.yml#L26).

Nice find. I forgot! It should be added now.

**Review by adri0 — APPROVED** [review]
Looks good to me :)

**Pull request merged**
