### PR TITLE
Drop explicit support for python 3.6 as it is end of life, add 3.10

### PR DESCRIPTION
**Pull request by timvink**
## Changed

- Drop explicit support for python 3.6 as it is end of life (package will still work on 3.6), see [stop using python 3.6](https://pythonspeed.com/articles/stop-using-python-3.6/)
- Added explicit support and unit testing for python 3.10

### CODE REVIEW

**Review by Matgrb — APPROVED** [review]
Thanks for this Tim

**Comment by Matgrb** [comment]
The tests fail, do you have any idea how to fix them?

**Comment by timvink** [comment]
The error is voor `llvm`, which is related to `numba` ([source](https://github.com/numba/llvmlite/issues/55), which in turn had issues with 3.10 that where very recently fixed ([issue](https://github.com/numba/numba/issues/7562)) but not yet released.

`shap` uses `numba` but luckily does not fix a version (see [here](https://github.com/slundberg/shap/blob/46b3800b31df04745416da27c71b216f91d61775/setup.py#L228)).

I'll watch for the next release of `numba` on pypi and then re-try this PR.

**Comment by timvink** [comment]
Works 🎉

**Comment by timvink** [comment]
( I merged as you had already approved the PR @Matgrb )

**Pull request merged**
