### PR TITLE
Fixing tests for shap==0.42.1

### PR DESCRIPTION
**Pull request by detrin**
https://github.com/ing-bank/probatus/issues/225

Also fixed one test for numpy>=1.24.0.

Btw, what is the suggested workflow with pre-commit? Add it into virtual env and commit from a command line after I used pre-commit run? Do you use vscode as well?

### CODE REVIEW

**Comment by detrin** [comment]
@ReinierKoops Could you have a look at this PR?

**Comment by ReinierKoops** [comment]
Lets see how it runs. Please have a look at the file https://github.com/ing-bank/probatus/blob/main/CONTRIBUTING.md

**Comment by ReinierKoops** [comment]
Thanks again, nice work!

**Comment by detrin** [comment]
@ReinierKoops I am glad to help :)

I followed the instructions, however I am not sure whether I should use pre-commit within venv or globally. Do yo personally use venv or poetry or something else?

**Comment by ReinierKoops** [comment]
Personally I use conda separate env to test it

**Review by ReinierKoops — APPROVED** [review]
Awesome work

**Pull request merged**
